oauth:
  consumer_key:    "YOUR_CONSUMER_KEY"
  consumer_secret: "YOUR_CONSUMER_SECRET"
  access_key:      "YOUR_ACCESS_KEY"
  access_secret:   "YOUR_ACCESS_SECRET"

account:
  user_id:     0 # your user_id
  screen_name: "YOUR_SCREEN_NAME"
